# Welcome to Jekyll!
# This config file contains site-wide settings.

# Site settings
title: Economy, Stock Market Investing & Trading
description: "A blog on stock market economy stock market investing & trading"
baseurl: "/stock-market-investing-trading.github.io" # Leave blank unless in a subdirectory
url: "https://saravana-tk.github.io"

# Theme settings
remote_theme: jekyll/minima  # Use remote theme for GitHub Pages

# Plugins for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-remote-theme  # Required for remote themes

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/